/* ═══════════════════════════════════════════════
   admin.js — 방문 통계 대시보드

   visits 테이블은 anon 키로 읽을 수 없다(읽기 정책이 없다). 관리자 토큰을
   인자로 받는 security definer 함수 admin_visits() 만 통과시켜 준다.
   토큰은 이 브라우저의 localStorage 에만 둔다.

   집계는 전부 브라우저에서 한다. 개인 사이트 규모에서는 몇천 줄을 받아
   계산하는 편이 서버에 집계 함수를 여러 개 만드는 것보다 단순하고,
   보고 싶은 지표가 늘어나도 SQL 을 다시 실행할 필요가 없다.
   ═══════════════════════════════════════════════ */
(function (TP) {

const u = TP.u, $ = u.$;

const K_TOKEN  = 'ticketrush.admin.token';
const LIVE_MS  = 3 * 60 * 1000;    // 이 시간 안에 신호가 있으면 '접속 중'
const AUTO_MS  = 20000;
const HOUR = 3600e3, DAY = 86400e3;

/* 화면 id → 사람이 읽는 이름 */
const STAGE_NAME = {
  home: '홈', standby: '오픈 대기', queue: '대기열', captcha: '보안문자',
  schedule: '회차 선택', zone: '구역 선택', seat: '좌석 선택',
  checkout: '결제', result: '분석 결과',
  'online-rank': '온라인 랭킹', duel: '실시간 대결',
  'cd-setup': '보안문자 연습 설정', 'cd-run': '보안문자 연습', 'cd-result': '보안문자 연습 결과'
};

/* 이탈 지점을 보려면 순서가 고정돼야 한다 — 연습 한 판의 정규 경로 */
const FUNNEL = ['home', 'standby', 'queue', 'captcha', 'schedule', 'zone', 'seat', 'checkout', 'result'];

const RANGES = {
  '24h': { ms: DAY,      step: HOUR, n: 24, label: '최근 24시간' },
  '7d':  { ms: 7 * DAY,  step: DAY,  n: 7,  label: '최근 7일' },
  '30d': { ms: 30 * DAY, step: DAY,  n: 30, label: '최근 30일' },
  'all': { ms: null,     step: DAY,  n: 60, label: '전체 기간' }
};

const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, ch => (
  { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]
));

/* 설정 SQL — sql/admin.sql 과 같은 내용이며 토큰만 채워 넣는다 */
const sqlFor = (token) =>
`create table if not exists public.visits (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  sid         text not null,
  kind        text not null,
  stage       text,
  nick        text,
  difficulty  text,
  venue       text,
  concert     text,
  device      text,
  browser     text,
  os          text,
  ref         text,
  lang        text,
  tz          text,
  pwa         boolean not null default false,
  is_return   boolean not null default false,
  dur_ms      integer
);

create index if not exists visits_created_idx on public.visits (created_at desc);
create index if not exists visits_sid_idx     on public.visits (sid);

alter table public.visits enable row level security;

drop policy if exists "anyone can insert visit" on public.visits;
create policy "anyone can insert visit"
  on public.visits for insert with check (true);

create or replace function public.admin_visits(token text, since timestamptz, lim int)
returns setof public.visits
language plpgsql
security definer
set search_path = public
as $$
begin
  if token is distinct from '${token}' then
    raise exception 'unauthorized' using errcode = '42501';
  end if;

  return query
    select * from public.visits
    where created_at >= since
    order by created_at desc
    limit least(coalesce(lim, 20000), 50000);
end;
$$;

revoke all on function public.admin_visits(text, timestamptz, int) from public;
grant execute on function public.admin_visits(text, timestamptz, int) to anon;

notify pgrst, 'reload schema';`;

/* ═══════════════════════════════════════════════ */

const A = {
  token: null,
  range: '24h',
  rows: [],
  scores: [],
  scoreTotal: 0,
  timer: null,
  busy: false,

  init() {
    try { this.token = localStorage.getItem(K_TOKEN) || null; } catch (e) {}

    const tokenInput = $('#adm-token');
    const paint = () => { $('#adm-sql').textContent = sqlFor(tokenInput.value.trim() || 'CHANGE-ME-ADMIN-TOKEN'); };
    tokenInput.addEventListener('input', paint);
    paint();

    $('#adm-enter').onclick = () => this.enter(tokenInput.value.trim());
    tokenInput.addEventListener('keydown', (e) => { if (e.key === 'Enter') this.enter(tokenInput.value.trim()); });

    $('#adm-copy-sql').onclick = () => {
      const text = $('#adm-sql').textContent;
      const done = () => { $('#adm-copy-sql').textContent = '복사됨'; setTimeout(() => { $('#adm-copy-sql').textContent = 'SQL 복사'; }, 1500); };
      if (navigator.clipboard) navigator.clipboard.writeText(text).then(done).catch(() => {});
      else done();
    };

    u.$$('#adm-range button').forEach(b => {
      b.onclick = () => {
        this.range = b.dataset.range;
        u.$$('#adm-range button').forEach(x => x.classList.toggle('on', x === b));
        this.load();
      };
    });
    $('#adm-refresh').onclick = () => this.load();
    $('#adm-auto').onchange = () => this.setAuto($('#adm-auto').checked);
    $('#adm-logout').onclick = () => {
      if (!confirm('저장된 관리자 토큰을 지울까요?')) return;
      try { localStorage.removeItem(K_TOKEN); } catch (e) {}
      location.reload();
    };

    if (this.token) { tokenInput.value = this.token; paint(); this.enter(this.token); }
  },

  /* ─────────── 진입 ─────────── */

  /** 토큰이 맞는지 한 줄만 받아보고 통과시킨다 */
  async enter(token) {
    if (!token || token.length < 4) { this.gateError('토큰을 입력해 주세요.'); return; }
    this.token = token;

    const probe = await this.fetchVisits(new Date(Date.now() - HOUR).toISOString(), 1);
    if (!probe.ok) { this.gateError(probe.text); return; }

    try { localStorage.setItem(K_TOKEN, token); } catch (e) {}
    $('#adm-gate').classList.add('hidden');
    $('#adm-main').classList.remove('hidden');
    this.setAuto($('#adm-auto').checked);
    this.load();
  },

  gateError(text) {
    const el = $('#adm-gate-err');
    el.textContent = text || '통계를 열 수 없습니다.';
    el.classList.remove('hidden');
    $('#adm-gate').classList.remove('hidden');
    $('#adm-main').classList.add('hidden');
  },

  setAuto(on) {
    clearInterval(this.timer);
    if (on) this.timer = setInterval(() => this.load(true), AUTO_MS);
  },

  /* ─────────── 서버 조회 ─────────── */

  /** 서버 응답을 짐작하지 않고 그대로 해석한다 (leaderboard.js 와 같은 방식) */
  explain(code, body) {
    let j = null;
    try { j = JSON.parse(body); } catch (e) {}
    const msg = (j && (j.message || j.hint || j.error)) || '';
    const pg  = (j && j.code) || '';

    if (/unauthorized/i.test(msg) || pg === '42501') {
      return { ok: false, text: '토큰이 맞지 않습니다. Supabase 의 admin_visits 함수에 넣은 값과 같은지 확인해 주세요.' };
    }
    if (pg === 'PGRST202' || code === 404 || /schema cache|could not find/i.test(msg)) {
      return { ok: false, text: '아래 설정 SQL 을 아직 실행하지 않았습니다. 펼쳐서 실행한 뒤 다시 시도해 주세요.' };
    }
    if (code === 401 || code === 403) {
      return { ok: false, text: 'Supabase 키가 거부되었습니다. js/sb.js 의 anon 키를 확인해 주세요.' };
    }
    return { ok: false, text: `서버 오류 ${code}${pg ? ' / ' + pg : ''}${msg ? ' — ' + msg : ''}` };
  },

  async fetchVisits(sinceISO, lim) {
    try {
      const res = await fetch(`${TP.SB.URL}/rest/v1/rpc/admin_visits`, {
        method: 'POST',
        headers: TP.SB.headers(),
        body: JSON.stringify({ token: this.token, since: sinceISO, lim: lim || 20000 })
      });
      if (!res.ok) return this.explain(res.status, await res.text());
      return { ok: true, rows: await res.json() };
    } catch (e) {
      return { ok: false, text: '서버에 연결할 수 없습니다. 인터넷 연결을 확인해 주세요.' };
    }
  },

  /** 온라인 랭킹 기록 — scores 는 공개 읽기라 anon 키로 바로 받는다 */
  async fetchScores() {
    const h = TP.SB.headers();
    try {
      const [listRes, cntRes] = await Promise.all([
        fetch(`${TP.SB.URL}/rest/v1/scores?select=nick,difficulty,reaction_ms,score,success,created_at`
              + `&order=created_at.desc&limit=12`, { headers: h }),
        fetch(`${TP.SB.URL}/rest/v1/scores?select=id`, {
          headers: Object.assign({}, h, { 'Prefer': 'count=exact', 'Range-Unit': 'items', 'Range': '0-0' })
        })
      ]);
      const rows = listRes.ok ? await listRes.json() : [];
      let total = 0;
      if (cntRes.ok) {
        const cr = cntRes.headers.get('content-range') || '';
        const n = parseInt(cr.split('/')[1] || '', 10);
        total = isFinite(n) ? n : 0;
      }
      return { rows, total };
    } catch (e) {
      return { rows: [], total: 0 };
    }
  },

  async load(quiet) {
    if (this.busy) return;
    this.busy = true;
    const st = $('#adm-status');
    if (!quiet) { st.className = 'adm-status'; st.textContent = '불러오는 중...'; }

    const r = RANGES[this.range];
    const sinceISO = r.ms ? new Date(Date.now() - r.ms).toISOString() : '1970-01-01T00:00:00Z';

    const [vis, sc] = await Promise.all([this.fetchVisits(sinceISO), this.fetchScores()]);
    this.busy = false;

    if (!vis.ok) {
      st.className = 'adm-status err';
      st.textContent = vis.text;
      return;
    }

    // 최신순 정렬을 여기서 한 번 보장한다 — 아래 집계가 '가장 최근 값'을 앞에서 집는다
    this.rows = vis.rows.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
    this.scores = sc.rows;
    this.scoreTotal = sc.total;

    st.className = 'adm-status';
    st.textContent = `${r.label} · 기록 ${u.n(this.rows.length)}줄 · ${u.hhmmss(new Date())} 기준`;
    this.render();
  },

  /* ─────────── 집계 ─────────── */

  /** 줄 단위 기록을 방문(세션) 단위로 접는다 */
  sessions() {
    const m = new Map();
    const META = ['device', 'browser', 'os', 'ref', 'lang', 'tz', 'venue', 'difficulty', 'concert', 'nick'];

    for (const r of this.rows) {                       // 최신 → 과거 순서
      const t = new Date(r.created_at).getTime();
      let s = m.get(r.sid);
      if (!s) {
        s = { sid: r.sid, first: t, last: t, stages: new Set(), dur: 0, n: 0, lastStage: null, lastKind: r.kind };
        m.set(r.sid, s);
      }
      if (t < s.first) s.first = t;
      if (t > s.last)  s.last = t;
      s.n++;
      if (r.stage) {
        s.stages.add(r.stage);
        if (!s.lastStage) s.lastStage = r.stage;       // 최신순이라 처음 만나는 값이 가장 최근이다
      }
      if (r.kind === 'end' && r.dur_ms) s.dur = Math.max(s.dur, r.dur_ms);
      if (r.pwa) s.pwa = true;
      if (r.is_return) s.ret = true;
      for (const k of META) if (r[k] && !s[k]) s[k] = r[k];
    }
    return Array.from(m.values());
  },

  countBy(list, key) {
    const m = new Map();
    list.forEach(s => {
      const v = s[key];
      if (!v) return;
      m.set(v, (m.get(v) || 0) + 1);
    });
    return Array.from(m.entries()).sort((a, b) => b[1] - a[1]);
  },

  /** 방문 시작 시각으로 구간을 나눈다 */
  series(ss) {
    const r = RANGES[this.range];
    const daily = r.step === DAY;
    const now = new Date();

    let n = r.n;
    if (this.range === 'all') {
      const first = ss.length ? Math.min.apply(null, ss.map(s => s.first)) : Date.now();
      n = u.clamp(Math.ceil((Date.now() - first) / DAY) + 1, 1, 60);
    }

    const anchor = daily
      ? new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime()
      : new Date(now.getFullYear(), now.getMonth(), now.getDate(), now.getHours()).getTime();
    const start = anchor - (n - 1) * r.step;

    const buckets = new Array(n).fill(0);
    ss.forEach(s => {
      const i = Math.floor((s.first - start) / r.step);
      if (i >= 0 && i < n) buckets[i]++;
    });

    const labelAt = (i) => {
      const d = new Date(start + i * r.step);
      return daily ? `${d.getMonth() + 1}/${d.getDate()}` : `${d.getHours()}시`;
    };
    return { buckets, labelAt, n, daily };
  },

  /* ─────────── 그리기 ─────────── */

  render() {
    const ss = this.sessions();
    const now = Date.now();

    const live = ss.filter(s => s.last >= now - LIVE_MS && s.lastKind !== 'end')
                   .sort((a, b) => b.last - a.last);
    const done = ss.filter(s => s.stages.has('result'));
    const started = ss.filter(s => s.stages.has('standby') || s.stages.has('queue'));
    const fresh = ss.filter(s => !s.ret);

    const durs = ss.map(s => s.dur || (s.last - s.first)).filter(v => v > 1000);
    const medDur = u.median(durs);

    $('#adm-body').innerHTML = [
      this.kpis(ss, live, done, started, fresh, medDur),
      this.liveCard(live),
      `<div class="adm-grid c2">${this.seriesCard(ss)}${this.funnelCard(ss)}</div>`,
      `<div class="adm-grid c3">
         ${this.listCard('유입 경로', this.countBy(ss, 'ref').map(([k, v]) => [k === 'direct' ? '직접 방문' : k === 'internal' ? '사이트 내부' : k, v]), ss.length)}
         ${this.listCard('기기 · 브라우저', this.deviceList(ss), ss.length)}
         ${this.listCard('고른 공연장 · 난이도', this.choiceList(ss), ss.length)}
       </div>`,
      `<div class="adm-grid c2">${this.logCard()}${this.scoreCard()}</div>`
    ].join('');
  },

  kpis(ss, live, done, started, fresh, medDur) {
    const rate = started.length ? done.length / started.length * 100 : 0;
    const card = (cls, lab, val, unit, sub) => `
      <div class="kpi${cls ? ' ' + cls : ''}">
        <div class="kpi-lab">${cls === 'live' ? '<i class="dot"></i>' : ''}${lab}</div>
        <div class="kpi-val">${val}${unit ? `<span>${unit}</span>` : ''}</div>
        <div class="kpi-sub">${sub || ''}</div>
      </div>`;

    return `<div class="adm-kpis">
      ${card('live', '지금 접속 중', u.n(live.length), '명', '최근 3분 이내 활동')}
      ${card('', '방문', u.n(ss.length), '회', `신규 ${u.n(fresh.length)} · 재방문 ${u.n(ss.length - fresh.length)}`)}
      ${card('', '연습 시작', u.n(started.length), '회', '오픈 대기까지 진입')}
      ${card('', '끝까지 완주', u.n(done.length), '회', '분석 결과 화면 도달')}
      ${card('', '완주율', rate.toFixed(0), '%', '시작한 판 기준')}
      ${card('', '체류시간 중앙값', medDur == null ? '—' : u.dur(medDur / 1000), '', '한 방문에 머문 시간')}
    </div>`;
  },

  liveCard(live) {
    const body = live.length
      ? `<div class="now">${live.slice(0, 40).map(s => `
          <div class="nowc">
            <span class="logs" style="background:${this.hue(s.sid)}">${esc(s.sid.slice(0, 4))}</span>
            <span><b>${esc(STAGE_NAME[s.lastStage] || s.lastStage || '—')}</b> · ${esc(s.device || '')}${s.nick ? ' · ' + esc(s.nick) : ''}</span>
          </div>`).join('')}</div>`
      : `<p class="adm-empty">지금 사이트를 보고 있는 사람이 없습니다.</p>`;

    return `<div class="adm-card" style="margin-bottom:14px">
      <h2>지금 접속 중인 사람<em>어느 화면에 있는지</em></h2>${body}</div>`;
  },

  seriesCard(ss) {
    const { buckets, labelAt, n, daily } = this.series(ss);
    const max = Math.max.apply(null, buckets.concat([1]));
    const bars = buckets.map((v, i) => `
      <div class="tsb${v ? '' : ' empty'}" title="${labelAt(i)} · ${v}회">
        <i style="height:${v ? Math.max(4, v / max * 100) : 3}%"></i>
      </div>`).join('');

    const mid = Math.floor(n / 2);
    return `<div class="adm-card">
      <h2>방문 추이<em>${daily ? '하루' : '한 시간'} 단위 · 최대 ${max}회</em></h2>
      <div class="tsr">${bars}</div>
      <div class="tsx"><span>${labelAt(0)}</span><span>${labelAt(mid)}</span><span>${labelAt(n - 1)}</span></div>
    </div>`;
  },

  funnelCard(ss) {
    const total = ss.length || 1;
    let prev = null;

    const rows = FUNNEL.map(st => {
      const c = ss.filter(s => s.stages.has(st)).length;
      const drop = prev != null && prev > 0 ? (prev - c) / prev * 100 : null;
      prev = c;
      return `<div class="fnr${st === 'result' ? ' done' : ''}">
          <b>${STAGE_NAME[st]}</b>
          <div class="fnbar"><i style="width:${(c / total * 100).toFixed(1)}%"></i></div>
          <div class="fnn">${u.n(c)}${drop != null && drop > 0 ? `<em class="drop">-${drop.toFixed(0)}%</em>` : ''}</div>
        </div>`;
    }).join('');

    return `<div class="adm-card">
      <h2>단계별 이탈<em>방문 ${u.n(ss.length)}회 기준</em></h2>
      <div class="fn">${rows}</div>
    </div>`;
  },

  deviceList(ss) {
    const dev = { mobile: '모바일', tablet: '태블릿', desktop: 'PC' };
    const out = this.countBy(ss, 'device').map(([k, v]) => [dev[k] || k, v]);
    const pwa = ss.filter(s => s.pwa).length;
    if (pwa) out.push(['앱으로 설치해 사용', pwa]);
    return out.concat(this.countBy(ss, 'browser'));
  },

  choiceList(ss) {
    return this.countBy(ss, 'venue').concat(this.countBy(ss, 'difficulty'));
  },

  listCard(title, entries, total) {
    if (!entries.length) return `<div class="adm-card"><h2>${title}</h2><p class="lst-empty">아직 자료가 없습니다.</p></div>`;
    const max = entries[0][1] || 1;
    const rows = entries.slice(0, 8).map(([k, v]) => `
      <div class="lstr">
        <span class="lstn">${esc(k)}</span>
        <span class="lstv">${u.n(v)}</span>
      </div>
      <div class="lstbar"><i style="width:${(v / max * 100).toFixed(1)}%"></i></div>`).join('');
    return `<div class="adm-card"><h2>${title}<em>방문 수</em></h2><div class="lst">${rows}</div></div>`;
  },

  /** sid 를 색으로 바꿔 같은 사람의 줄을 눈으로 묶을 수 있게 한다 */
  hue(sid) {
    let h = 0;
    for (let i = 0; i < sid.length; i++) h = (h * 31 + sid.charCodeAt(i)) % 360;
    return `hsl(${h} 62% 45%)`;
  },

  logCard() {
    // ping 은 '살아있음' 신호일 뿐이라 로그에서는 뺀다 — 넣으면 진짜 행동이 묻힌다
    const rows = this.rows.filter(r => r.kind !== 'ping').slice(0, 80);
    if (!rows.length) return `<div class="adm-card"><h2>활동 기록</h2><p class="adm-empty">아직 기록이 없습니다.</p></div>`;

    const body = rows.map(r => {
      const d = new Date(r.created_at);
      let msg;
      if (r.kind === 'visit') {
        msg = `<b class="k-visit">입장</b> · ${esc(r.ref === 'direct' ? '직접 방문' : r.ref || '')}${r.is_return ? ' · 재방문' : ' · 처음'}`;
      } else if (r.kind === 'end') {
        msg = `<b class="k-end">나감</b> · ${esc(STAGE_NAME[r.stage] || r.stage || '')}에서${r.dur_ms ? ' · ' + u.dur(r.dur_ms / 1000) + ' 머무름' : ''}`;
      } else {
        msg = `<b>${esc(STAGE_NAME[r.stage] || r.stage || '?')}</b> 화면`;
      }
      return `<div class="logr">
          <span class="logt">${u.hhmmss(d)}</span>
          <span class="logs" style="background:${this.hue(r.sid)}">${esc(String(r.sid).slice(0, 4))}</span>
          <span class="logm">${msg}</span>
          <span class="logd">${esc(r.device || '')}${r.nick ? ' · ' + esc(r.nick) : ''}</span>
        </div>`;
    }).join('');

    return `<div class="adm-card"><h2>활동 기록<em>최근 ${rows.length}건 · 체류 확인 신호 제외</em></h2>
      <div class="log">${body}</div></div>`;
  },

  scoreCard() {
    if (!this.scores.length) {
      return `<div class="adm-card"><h2>온라인 랭킹 등록</h2><p class="adm-empty">아직 등록된 기록이 없습니다.</p></div>`;
    }
    const rows = this.scores.map(s => `
      <tr>
        <td>${esc(s.nick)}</td>
        <td>${esc(s.difficulty || '')}</td>
        <td class="num">${u.ms(s.reaction_ms)}</td>
        <td class="${s.success ? 'ok' : 'no'}">${s.success ? '성공' : '실패'}</td>
      </tr>`).join('');

    return `<div class="adm-card">
      <h2>온라인 랭킹 등록<em>누적 ${u.n(this.scoreTotal)}건</em></h2>
      <table class="tbl">
        <thead><tr><th>닉네임</th><th>난이도</th><th style="text-align:right">반응속도</th><th>결과</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`;
  }
};

TP.Admin = A;
document.addEventListener('DOMContentLoaded', () => A.init());

})(window.TP = window.TP || {});
