/* ═══════════════════════════════════════════════
   chat.js — 커뮤니티 (실시간 채팅 · 꿀팁 · 공연장 시야 질문)

   Supabase 를 백엔드로 쓴다. 라이브러리를 받지 않고 REST(PostgREST) 만
   직접 호출한다. 이 프로젝트는 파일만 열어도 돌아가야 하므로
   외부 스크립트 의존을 만들지 않는 편이 낫다.
   갱신은 3초 폴링이다. 이 규모의 채팅방에서는 체감 차이가 없고
   WebSocket 프로토콜을 직접 구현하는 비용이 훨씬 크다.

   접속 정보(프로젝트 URL · anon 키)는 코드에 박지 않고
   설정 화면에서 입력받아 이 브라우저의 localStorage 에만 저장한다.
   anon 키는 공개용으로 설계된 키이며, 실제 권한은 서버의 RLS 정책이 정한다.

   ※ 다른 사람이 쓴 메시지는 전부 데이터로만 다룬다.
     본문은 반드시 textContent 로 넣는다 (innerHTML 금지 — 스크립트 주입 방지).
   ═══════════════════════════════════════════════ */
(function (TP) {

const u = TP.u, $ = u.$;

const K_URL = 'ticketrush.supabase.url';
const K_KEY = 'ticketrush.supabase.key';
const POLL_MS = 3000;
const MAX_LEN = 500;
const SEND_GAP = 1000;          // 연타 방지

const ROOMS = [
  { id: 'all',      name: '전체',       desc: '아무 이야기나' },
  { id: 'tips',     name: '꿀팁',       desc: '티켓팅 노하우 공유' },
  { id: 'hall',     name: '콘서트홀',   desc: '예술의전당 시야' },
  { id: 'gym',      name: '실내체육관', desc: '잠실실내체육관 시야' },
  { id: 'inspire',  name: '아레나',     desc: '인스파이어 시야' },
  { id: 'arena',    name: '체조경기장', desc: 'KSPO DOME 시야' },
  { id: 'dome',     name: '돔구장',     desc: '고척스카이돔 시야' },
  { id: 'stadium',  name: '주경기장',   desc: '서울월드컵경기장 시야' }
];

/* 설정 안내에 그대로 보여줄 SQL
     · public 스키마를 명시한다 — REST 는 public 스키마만 노출한다.
     · 정책은 drop 후 create 한다 — 두 번 실행해도 오류가 나지 않아야 한다. */
const SETUP_SQL =
`create table if not exists public.messages (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  room       text not null,
  nick       text not null,
  body       text not null check (char_length(body) between 1 and 500)
);

create index if not exists messages_room_id_idx on public.messages (room, id desc);

alter table public.messages enable row level security;

drop policy if exists "anyone can read"   on public.messages;
drop policy if exists "anyone can insert" on public.messages;

create policy "anyone can read"   on public.messages for select using (true);
create policy "anyone can insert" on public.messages for insert with check (true);`;

const Chat = {

  room: 'all',
  lastSent: 0,

  /* ─────────── 접속 설정 ─────────── */
  cfg() {
    try {
      const url = (localStorage.getItem(K_URL) || '').trim().replace(/\/+$/, '');
      const key = (localStorage.getItem(K_KEY) || '').trim();
      return url && key ? { url, key } : null;
    } catch (e) { return null; }
  },

  saveCfg(url, key) {
    try {
      localStorage.setItem(K_URL, url.trim().replace(/\/+$/, ''));
      localStorage.setItem(K_KEY, key.trim());
    } catch (e) {}
  },

  clearCfg() {
    try { localStorage.removeItem(K_URL); localStorage.removeItem(K_KEY); } catch (e) {}
  },

  /* Supabase 키 형식이 두 가지다.
       예전: anon public — eyJ... (JWT)
       지금: Publishable  — sb_publishable_...
     역할(anon)을 고르는 건 apikey 헤더이므로 그것만 있으면 읽고 쓸 수 있다.
     Authorization: Bearer 는 JWT 일 때만 붙인다 — 새 형식에 붙이면 거부될 수 있다. */
  headers(c) {
    const h = { 'apikey': c.key, 'Content-Type': 'application/json' };
    if (/^ey[A-Za-z0-9_-]/.test(c.key)) h['Authorization'] = 'Bearer ' + c.key;
    return h;
  },

  /* ─────────── 진입 · 이탈 ─────────── */
  init() {
    const home = $('#btn-chat-home');
    if (home) home.onclick = () => this.exit();

    $('#btn-chat-send').onclick = () => this.send();
    $('#chat-input').onkeydown = e => {
      if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); this.send(); }
    };
    $('#btn-chat-save').onclick = () => {
      const url = $('#chat-url').value, key = $('#chat-key').value;
      if (!url.trim() || !key.trim()) { TP.ui.toast('주소와 키를 모두 넣어주세요.', 'warn'); return; }
      this.saveCfg(url, key);
      TP.ui.toast('저장했습니다. 연결을 확인합니다.', 'ok');
      this.render();
    };
    $('#btn-chat-reset').onclick = () => {
      if (!confirm('저장된 접속 정보를 지울까요?')) return;
      this.clearCfg();
      this.stop();
      this.render();
    };
    $('#chat-sql').textContent = SETUP_SQL;
    $('#chat-fix-sql').textContent = SETUP_SQL;

    this.buildRooms();
  },

  open() {
    TP.ui.topbar(false);
    if (TP.App && TP.App.hideMenuHint) TP.App.hideMenuHint();
    TP.ui.show('chat');
    this.render();
  },

  exit() {
    this.stop();
    if (TP.App && TP.App.goHome) TP.App.goHome();
    else TP.ui.show('home');
  },

  stop() {
    clearInterval(this._poll);
    this._poll = null;
  },

  /* ─────────── 방 목록 ─────────── */
  buildRooms() {
    const box = $('#chat-rooms');
    box.textContent = '';
    ROOMS.forEach(r => {
      const b = u.el('button.chat-room', { type: 'button', 'data-room': r.id, title: r.desc });
      b.appendChild(u.el('b', { text: r.name }));
      b.addEventListener('click', () => {
        this.room = r.id;
        this.paintRooms();
        this.load(true);
      });
      box.appendChild(b);
    });
    this.paintRooms();
  },

  paintRooms() {
    u.$$('.chat-room').forEach(b => b.classList.toggle('on', b.dataset.room === this.room));
    const r = ROOMS.find(x => x.id === this.room);
    $('#chat-room-desc').textContent = r ? r.desc : '';
  },

  /* ─────────── 화면 상태 ─────────── */
  render() {
    const c = this.cfg();
    $('#chat-setup').classList.toggle('hidden', !!c);
    $('#chat-live').classList.toggle('hidden', !c);
    if (!c) { this.stop(); return; }

    const nick = (TP.rank && TP.rank.player ? TP.rank.player() : '') || '';
    $('#chat-nick').textContent = nick || '이름 없음';
    $('#chat-nick-warn').classList.toggle('hidden', !!nick);

    this.load(true);
    this.stop();
    this._poll = setInterval(() => this.load(false), POLL_MS);
  },

  status(text, bad) {
    const el = $('#chat-status');
    el.textContent = text || '';
    el.classList.toggle('bad', !!bad);
    // 테이블·정책 문제일 때만 SQL 을 함께 띄운다 (해당 안내 문구에 SQL 이라는 말이 들어 있다)
    const needSql = !!bad && /SQL/.test(text || '');
    $('#chat-fix').classList.toggle('hidden', !needSql);
    // 스키마 캐시 문제는 SQL 을 또 실행할 게 아니라 캐시만 새로 읽으면 된다
    $('#chat-reload').classList.toggle('hidden', !(bad && /schema/i.test(text || '')));
  },

  /* ─────────── 읽기 ─────────── */
  async load(scroll) {
    const c = this.cfg();
    if (!c) return;
    const url = `${c.url}/rest/v1/messages`
      + `?select=id,created_at,room,nick,body`
      + `&room=eq.${encodeURIComponent(this.room)}`
      + `&order=id.desc&limit=60`;
    try {
      const res = await fetch(url, { headers: this.headers(c) });
      if (!res.ok) {
        const t = await res.text();
        this.status(this.explain(res.status, t), true);
        return;
      }
      const rows = await res.json();
      this.status('');
      this.paintMessages(rows.reverse(), scroll);
    } catch (e) {
      this.status('연결할 수 없습니다. 인터넷 연결과 프로젝트 주소를 확인해 주세요.', true);
    }
  },

  /* 원인을 짐작하지 말고 서버가 실제로 준 메시지를 그대로 보여준다.
     PostgREST 는 원인별로 코드를 준다 — 그걸로 안내를 갈라야 정확하다. */
  explain(code, body) {
    let j = null;
    try { j = JSON.parse(body); } catch (e) {}
    const msg = (j && (j.message || j.error_description || j.error || j.hint)) || '';
    const pg = (j && j.code) || '';
    const raw = msg ? ` — 서버 메시지: ${msg}` : (body ? ` — ${String(body).slice(0, 140)}` : '');

    // 테이블은 만들었는데 API 서버가 아직 모르는 상태. 가장 흔한 함정이다.
    if (pg === 'PGRST205' || /schema cache/i.test(msg)) {
      return 'SQL 은 성공했지만 API 서버가 아직 새 테이블을 인식하지 못했습니다. '
           + "SQL Editor 에서 notify pgrst, 'reload schema'; 를 실행하거나 30초쯤 기다려 주세요." + raw;
    }
    if (pg === '42P01' || /does not exist|relation .* not/i.test(msg)) {
      return '글을 저장할 messages 테이블이 없습니다. 아래 SQL 을 실행해 주세요.' + raw;
    }
    if (pg === '42501' || /permission denied/i.test(msg)) {
      return '테이블은 있지만 읽기·쓰기 권한이 없습니다. 아래 SQL 의 policy 부분을 실행해 주세요.' + raw;
    }
    if (code === 401 || code === 403) {
      return '키가 맞지 않거나 접근 정책이 없습니다. anon public(또는 Publishable) 키인지 확인하고 아래 SQL 을 실행해 주세요.' + raw;
    }
    if (code === 404) {
      return '주소가 Supabase API 주소가 아닐 수 있습니다. https://xxxx.supabase.co 형태여야 합니다 '
           + '(대시보드 주소를 붙여넣으면 이 오류가 납니다). 테이블이 없을 때도 같은 오류가 납니다 — 아래 SQL 을 실행해 주세요.' + raw;
    }
    return `서버 오류 ${code}${pg ? ' / ' + pg : ''}${raw}`;
  },

  paintMessages(rows, scroll) {
    const box = $('#chat-log');
    const nick = (TP.rank && TP.rank.player ? TP.rank.player() : '') || '이름 없음';

    // 내용이 같으면 다시 그리지 않는다 (3초마다 화면이 튀지 않도록)
    const sig = rows.map(r => r.id).join(',');
    if (sig === this._sig && !scroll) return;
    this._sig = sig;

    box.textContent = '';
    if (!rows.length) {
      box.appendChild(u.el('p.chat-empty', { text: '아직 글이 없습니다. 첫 글을 남겨보세요.' }));
      return;
    }

    rows.forEach(r => {
      const mine = r.nick === nick;
      const item = u.el('div.chat-msg' + (mine ? '.mine' : ''));
      const head = u.el('div.cm-head');
      // 닉네임과 본문은 다른 사람이 쓴 값이다 — 반드시 textContent 로만 넣는다
      head.appendChild(u.el('b', { text: r.nick || '이름 없음' }));
      head.appendChild(u.el('span', { text: this.when(r.created_at) }));
      item.appendChild(head);
      const body = u.el('div.cm-body');
      body.textContent = r.body || '';
      item.appendChild(body);
      box.appendChild(item);
    });

    if (scroll) box.scrollTop = box.scrollHeight;
    else if (box.scrollHeight - box.scrollTop - box.clientHeight < 120) box.scrollTop = box.scrollHeight;
  },

  when(iso) {
    const d = new Date(iso);
    if (isNaN(d)) return '';
    const p = n => String(n).padStart(2, '0');
    const today = new Date();
    const sameDay = d.toDateString() === today.toDateString();
    return sameDay ? `${p(d.getHours())}:${p(d.getMinutes())}`
                   : `${d.getMonth() + 1}.${d.getDate()} ${p(d.getHours())}:${p(d.getMinutes())}`;
  },

  /* ─────────── 쓰기 ─────────── */
  async send() {
    const c = this.cfg();
    if (!c) return;
    const inp = $('#chat-input');
    const body = inp.value.trim();
    if (!body) return;
    if (body.length > MAX_LEN) {
      TP.ui.toast(`${MAX_LEN}자까지 쓸 수 있습니다.`, 'warn');
      return;
    }
    const now = Date.now();
    if (now - this.lastSent < SEND_GAP) {
      TP.ui.toast('조금 천천히 보내주세요.', 'warn', 1400);
      return;
    }
    this.lastSent = now;

    const nick = ((TP.rank && TP.rank.player ? TP.rank.player() : '') || '이름 없음').slice(0, 12);
    const btn = $('#btn-chat-send');
    btn.disabled = true;
    try {
      const res = await fetch(`${c.url}/rest/v1/messages`, {
        method: 'POST',
        headers: this.headers(c),
        body: JSON.stringify({ room: this.room, nick: nick, body: body })
      });
      if (!res.ok) {
        const t = await res.text();
        this.status(this.explain(res.status, t), true);
        return;
      }
      inp.value = '';
      this._sig = null;              // 방금 쓴 글이 바로 보이게 강제 갱신
      this.load(true);
    } catch (e) {
      this.status('전송하지 못했습니다. 연결을 확인해 주세요.', true);
    } finally {
      btn.disabled = false;
    }
  }
};

TP.Chat = Chat;
document.addEventListener('DOMContentLoaded', () => Chat.init());

})(window.TP = window.TP || {});
