/* ═══════════════════════════════════════════════
   duel.js — 실시간 대결 (방 코드, Supabase REST 폴링)

   온라인 랭킹과 같은 Supabase 프로젝트를 그대로 쓴다(TP.Leaderboard.cfg()).
   실시간이라고 해도 웹소켓을 새로 붙이지 않고, 이 사이트의 다른 REST
   호출들과 같은 방식으로 짧은 주기 폴링만 한다 — 서버·클라이언트 모두
   더 가볍고, 이 대결 하나에 필요한 정확도(초 단위 카운트다운 + 클릭
   반응속도)에는 폴링만으로 충분하다.

   진행
     로비(대기실) → 2명 이상 전원 준비 → 서버가 시작 시각(start_at)을
     한 번만 확정 → 모든 참가자가 그 절대 시각 기준으로 각자 카운트다운
     → 신호가 뜨면 버튼 클릭까지 걸린 시간을 서버에 제출 → 전원 제출되면
     결과.

   동시 시작 경쟁
     "모두 준비됨"을 본 클라이언트가 각자 방을 countdown 으로 바꾸려
     시도하지만, PATCH 조건에 status=eq.lobby 를 걸어서 먼저 성공한
     한 번만 반영되고 나머지는 조용히 무시된다 — 별도 방장 개념이
     필요 없다.
   ═══════════════════════════════════════════════ */
(function (TP) {

const u = TP.u, $ = u.$;
const enc = encodeURIComponent;

const SETUP_SQL =
`create table if not exists public.duel_rooms (
  code         text primary key,
  created_at   timestamptz not null default now(),
  host_nick    text,
  status       text not null default 'lobby',
  start_at     timestamptz
);

create table if not exists public.duel_players (
  id           bigint generated by default as identity primary key,
  room_code    text not null references public.duel_rooms(code) on delete cascade,
  nick         text not null,
  joined_at    timestamptz not null default now(),
  ready        boolean not null default false,
  reaction_ms  integer,
  finished_at  timestamptz
);

create index if not exists duel_players_room_idx on public.duel_players (room_code);

alter table public.duel_rooms enable row level security;
alter table public.duel_players enable row level security;

drop policy if exists "anyone can read rooms" on public.duel_rooms;
drop policy if exists "anyone can insert rooms" on public.duel_rooms;
drop policy if exists "anyone can update rooms" on public.duel_rooms;
drop policy if exists "anyone can delete rooms" on public.duel_rooms;
create policy "anyone can read rooms" on public.duel_rooms for select using (true);
create policy "anyone can insert rooms" on public.duel_rooms for insert with check (true);
create policy "anyone can update rooms" on public.duel_rooms for update using (true);
create policy "anyone can delete rooms" on public.duel_rooms for delete using (true);

drop policy if exists "anyone can read players" on public.duel_players;
drop policy if exists "anyone can insert players" on public.duel_players;
drop policy if exists "anyone can update players" on public.duel_players;
drop policy if exists "anyone can delete players" on public.duel_players;
create policy "anyone can read players" on public.duel_players for select using (true);
create policy "anyone can insert players" on public.duel_players for insert with check (true);
create policy "anyone can update players" on public.duel_players for update using (true);
create policy "anyone can delete players" on public.duel_players for delete using (true);`;

const CODE_CHARS = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; // 0·O·1·I·L 제외 (보안문자와 같은 이유)

const Duel = {

  room: null,   // { code, playerId, nick, players, status, startAt }

  /* ─────────── 진입 · 이탈 ─────────── */
  open() {
    TP.ui.topbar(false);
    if (TP.App && TP.App.hideMenuHint) TP.App.hideMenuHint();
    this.stopPoll();
    this.stopHomePoll();
    clearTimeout(this._goTimer);
    clearInterval(this._cdTimer);
    this.room = null;
    TP.ui.show('duel');
    this.renderHome();
  },

  exit() {
    this.stopPoll();
    this.stopHomePoll();
    clearTimeout(this._goTimer);
    clearInterval(this._cdTimer);
    this.room = null;
    if (TP.App && TP.App.goHome) TP.App.goHome();
    else TP.ui.show('home');
  },

  stopPoll() { clearInterval(this._pollTimer); this._pollTimer = null; },
  stopHomePoll() { clearInterval(this._homePollTimer); this._homePollTimer = null; },

  genCode() {
    let s = '';
    for (let i = 0; i < 5; i++) s += CODE_CHARS[Math.floor(Math.random() * CODE_CHARS.length)];
    return s;
  },

  /* ─────────── 서버 오류 해석 (leaderboard.js 와 같은 방식) ─────────── */
  explain(code, body) {
    let j = null;
    try { j = JSON.parse(body); } catch (e) {}
    const msg = (j && (j.message || j.error_description || j.error || j.hint)) || '';
    const pg = (j && j.code) || '';
    const raw = msg ? ` — 서버 메시지: ${msg}` : (body ? ` — ${String(body).slice(0, 140)}` : '');

    if (pg === 'PGRST205' || /schema cache/i.test(msg)) {
      return { kind: 'reload', text: 'SQL 은 성공했지만 API 서버가 아직 새 테이블을 인식하지 못했습니다.' + raw };
    }
    if (pg === '42P01' || /does not exist|relation .* not/i.test(msg)) {
      return { kind: 'sql', text: '실시간 대결에 필요한 테이블이 아직 없습니다.' + raw };
    }
    if (pg === '42501' || /permission denied/i.test(msg)) {
      return { kind: 'sql', text: '테이블은 있지만 읽기·쓰기 권한이 없습니다.' + raw };
    }
    if (code === 401 || code === 403) {
      return { kind: 'sql', text: '접속 키가 맞지 않습니다.' + raw };
    }
    if (code === 404) {
      return { kind: 'sql', text: '주소가 Supabase API 주소가 아니거나 테이블이 없습니다.' + raw };
    }
    return { kind: 'sql', text: `서버 오류 ${code}${pg ? ' / ' + pg : ''}${raw}` };
  },

  showError(e) {
    const box = $('#duel-home-msg');
    if (!box) return;
    box.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };
    box.appendChild(H(`
      <div class="lb-fix">
        <b>${TP.Leaderboard.esc(e.text || '오류가 발생했습니다.')}</b>
        ${e.kind === 'sql' ? `<pre class="svc-sql">${TP.Leaderboard.esc(SETUP_SQL)}</pre><span>Supabase 대시보드 SQL Editor 에서 한 번만 실행하면 됩니다.</span>` : ''}
        ${e.kind === 'reload' ? `<pre class="svc-sql">notify pgrst, 'reload schema';</pre><span>이 한 줄만 SQL Editor 에서 실행하면 됩니다.</span>` : ''}
      </div>`));
  },

  setBusy(on) {
    const box = $('#duel-box');
    if (!box) return;
    u.$$('#btn-duel-create, #btn-duel-join', box).forEach(b => { b.disabled = on; });
  },

  /* ─────────── 홈 (방 만들기 · 코드로 입장) ─────────── */
  renderHome() {
    const box = $('#duel-box');
    box.innerHTML = `
      <button type="button" class="drill-back" id="btn-duel-back">← 전체 연습으로</button>
      <div class="home-hero" style="padding:30px 0 22px">
        <div class="hero-badge">실시간 대결</div>
        <h1 class="hero-title">친구랑 <em>진짜로</em> 겨룹니다.</h1>
        <p class="hero-sub">
          방 코드 하나로 몇 명이든 들어와서, 같은 순간에 뜨는 예매 버튼을 누가 더 빨리 누르는지 겨룹니다.<br>
          온라인 랭킹과 같은 서버를 쓰므로 별도 가입은 필요 없습니다.
        </p>
      </div>
      <div class="panel-block" style="max-width:640px;margin:0 auto">
        <div class="block-title">
          <span>지금 열려 있는 방</span>
          <button class="btn-link" id="btn-duel-refresh" type="button" style="margin-left:auto">새로고침</button>
        </div>
        <div class="rk-boardwrap">
          <div class="rk-board" id="duel-room-list"><p class="lb-loading">불러오는 중...</p></div>
        </div>
      </div>
      <div class="opt-grid" style="max-width:640px;margin:20px auto 0">
        <button class="venue-pick" id="btn-duel-create" type="button">
          <div class="vp-name">방 만들기</div>
          <div class="vp-desc">새 코드를 받아서 친구를 초대합니다.</div>
        </button>
        <div class="venue-pick">
          <div class="vp-name">코드로 바로 입장</div>
          <div class="vp-desc" style="margin-bottom:10px">친구에게 코드를 따로 받았다면 여기에 입력하세요.</div>
          <div class="dv-join-row">
            <input type="text" id="duel-code-input" class="dv-code-input" placeholder="코드 입력" maxlength="6" autocomplete="off" spellcheck="false">
            <button class="btn-primary" id="btn-duel-join" type="button">입장</button>
          </div>
        </div>
      </div>
      <div id="duel-home-msg" style="max-width:640px;margin:16px auto 0"></div>
    `;

    $('#btn-duel-back', box).onclick = () => this.exit();
    $('#btn-duel-create', box).onclick = () => this.createRoom();
    $('#btn-duel-join', box).onclick = () => this.joinRoom($('#duel-code-input', box).value);
    $('#duel-code-input', box).onkeydown = e => { if (e.key === 'Enter') this.joinRoom(e.target.value); };
    $('#btn-duel-refresh', box).onclick = () => this.refreshRoomList();

    this.refreshRoomList();
    this.startHomePoll();
  },

  startHomePoll() {
    this.stopHomePoll();
    this._homePollTimer = setInterval(() => this.refreshRoomList(), 2500);
  },

  /** 최근 30분 안에 만들어진, 아직 시작하지 않은 방만 보여준다 (정리 크론이 없어 오래된 방은 숨김) */
  async refreshRoomList() {
    const listEl = $('#duel-room-list');
    if (!listEl) return;
    const c = TP.Leaderboard.cfg();
    const since = new Date(Date.now() - 30 * 60 * 1000).toISOString();
    try {
      const res = await fetch(
        `${c.url}/rest/v1/duel_rooms?status=eq.lobby&created_at=gt.${enc(since)}&select=code,host_nick,created_at&order=created_at.desc&limit=15`,
        { headers: TP.Leaderboard.headers(c) }
      );
      // 자세한 오류는 만들기/입장을 실제로 시도할 때 보여준다 — 여기서는 목록을 그냥 빈 상태로 둔다
      this.renderRoomList(res.ok ? await res.json() : []);
    } catch (e) {
      this.renderRoomList([]);
    }
  },

  renderRoomList(rooms) {
    const listEl = $('#duel-room-list');
    if (!listEl) return;
    listEl.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };
    if (!rooms.length) {
      listEl.appendChild(H('<p class="lb-empty">지금 열려 있는 방이 없습니다. 방을 만들어서 친구를 초대해 보세요.</p>'));
      return;
    }
    rooms.forEach(r => {
      const row = H(`
        <div class="rk-row">
          <span class="rk-n">${TP.Leaderboard.esc(r.host_nick || '이름 없음')}님의 방 · <span style="font-family:var(--mono);color:var(--muted)">${TP.Leaderboard.esc(r.code)}</span></span>
          <button class="btn-ghost" type="button">입장</button>
        </div>`);
      row.querySelector('button').onclick = () => this.joinRoom(r.code);
      listEl.appendChild(row);
    });
  },

  async insertPlayer(c, code, nick) {
    try {
      const res = await fetch(`${c.url}/rest/v1/duel_players`, {
        method: 'POST',
        headers: Object.assign({}, TP.Leaderboard.headers(c), { Prefer: 'return=representation' }),
        body: JSON.stringify({ room_code: code, nick })
      });
      const text = await res.text();
      if (!res.ok) return Object.assign({ ok: false }, this.explain(res.status, text));
      const rows = JSON.parse(text);
      return { ok: true, id: rows[0].id };
    } catch (e) {
      return { ok: false, kind: 'net', text: '연결할 수 없습니다. 인터넷 연결을 확인해 주세요.' };
    }
  },

  async createRoom() {
    const c = TP.Leaderboard.cfg();
    const nick = (TP.rank.player() || '이름 없음').trim().slice(0, 12) || '이름 없음';
    this.setBusy(true);

    for (let attempt = 0; attempt < 5; attempt++) {
      const code = this.genCode();
      let res, text;
      try {
        res = await fetch(`${c.url}/rest/v1/duel_rooms`, {
          method: 'POST',
          headers: Object.assign({}, TP.Leaderboard.headers(c), { Prefer: 'return=representation' }),
          body: JSON.stringify({ code, host_nick: nick })
        });
        text = await res.text();
      } catch (e) {
        this.setBusy(false);
        return this.showError({ kind: 'net', text: '연결할 수 없습니다. 인터넷 연결을 확인해 주세요.' });
      }
      if (res.ok) {
        const joinRes = await this.insertPlayer(c, code, nick);
        this.setBusy(false);
        if (!joinRes.ok) return this.showError(joinRes);
        return this.enterRoom(code, joinRes.id, nick, true);
      }
      let j = null;
      try { j = JSON.parse(text); } catch (e) {}
      if (j && j.code === '23505') continue; // 코드 충돌 — 새 코드로 재시도
      this.setBusy(false);
      return this.showError(this.explain(res.status, text));
    }
    this.setBusy(false);
    this.showError({ text: '방 코드 생성에 계속 실패했습니다. 다시 시도해 주세요.' });
  },

  async joinRoom(codeRaw) {
    const code = (codeRaw || '').trim().toUpperCase();
    if (!code) { TP.ui.toast('방 코드를 입력해 주세요.', 'warn'); return; }
    const c = TP.Leaderboard.cfg();
    const nick = (TP.rank.player() || '이름 없음').trim().slice(0, 12) || '이름 없음';
    this.setBusy(true);
    try {
      const res = await fetch(`${c.url}/rest/v1/duel_rooms?code=eq.${enc(code)}&select=code,status`, { headers: TP.Leaderboard.headers(c) });
      const text = await res.text();
      if (!res.ok) { this.setBusy(false); return this.showError(this.explain(res.status, text)); }
      const rows = JSON.parse(text);
      if (!rows.length) { this.setBusy(false); return this.showError({ text: '존재하지 않는 방 코드입니다.' }); }
      if (rows[0].status !== 'lobby') { this.setBusy(false); return this.showError({ text: '이미 시작됐거나 끝난 방입니다.' }); }
      const joinRes = await this.insertPlayer(c, code, nick);
      this.setBusy(false);
      if (!joinRes.ok) return this.showError(joinRes);
      this.enterRoom(code, joinRes.id, nick, false);
    } catch (e) {
      this.setBusy(false);
      this.showError({ kind: 'net', text: '연결할 수 없습니다. 인터넷 연결을 확인해 주세요.' });
    }
  },

  /* ─────────── 로비(대기실) ─────────── */
  enterRoom(code, playerId, nick, isHost) {
    this.stopHomePoll();
    this.room = { code, playerId, nick, isHost: !!isHost, players: [], status: 'lobby', startAt: null };
    this.renderLobby();
    this.startLobbyPoll();
  },

  startLobbyPoll() {
    this.stopPoll();
    const tick = () => this.pollLobby();
    tick();
    this._pollTimer = setInterval(tick, 1200);
  },

  async pollLobby() {
    if (!this.room) return;
    const c = TP.Leaderboard.cfg(), code = this.room.code;
    try {
      const [roomRes, playersRes] = await Promise.all([
        fetch(`${c.url}/rest/v1/duel_rooms?code=eq.${enc(code)}&select=status,start_at`, { headers: TP.Leaderboard.headers(c) }),
        fetch(`${c.url}/rest/v1/duel_players?room_code=eq.${enc(code)}&select=id,nick,ready,reaction_ms&order=joined_at.asc`, { headers: TP.Leaderboard.headers(c) })
      ]);
      if (!roomRes.ok || !playersRes.ok || !this.room) return;
      const roomRows = await roomRes.json();
      const players = await playersRes.json();
      if (!this.room) return;
      if (!roomRows.length) {
        this.stopPoll();
        TP.ui.toast('방을 찾을 수 없습니다. 방이 삭제됐을 수 있습니다.', 'err');
        this.exit();
        return;
      }
      const room = roomRows[0];
      this.room.players = players;
      this.room.status = room.status;
      this.room.startAt = room.start_at;

      if (room.status === 'lobby') {
        if (players.length >= 2 && players.every(p => p.ready)) this.tryStart(code);
        this.renderLobby();
      } else {
        this.stopPoll();
        this.enterRace();
      }
    } catch (e) { /* 네트워크 일시 오류 — 다음 폴링에서 재시도 */ }
  },

  async tryStart(code) {
    if (this._starting) return;
    this._starting = true;
    const c = TP.Leaderboard.cfg();
    const startAt = new Date(Date.now() + 4000).toISOString();
    try {
      await fetch(`${c.url}/rest/v1/duel_rooms?code=eq.${enc(code)}&status=eq.lobby`, {
        method: 'PATCH',
        headers: Object.assign({}, TP.Leaderboard.headers(c), { Prefer: 'return=minimal' }),
        body: JSON.stringify({ status: 'countdown', start_at: startAt })
      });
    } catch (e) {}
    this._starting = false;
  },

  async toggleReady() {
    if (!this.room) return;
    const c = TP.Leaderboard.cfg();
    const me = this.room.players.find(p => p.id === this.room.playerId);
    const next = !(me && me.ready);
    try {
      await fetch(`${c.url}/rest/v1/duel_players?id=eq.${this.room.playerId}`, {
        method: 'PATCH',
        headers: Object.assign({}, TP.Leaderboard.headers(c), { Prefer: 'return=minimal' }),
        body: JSON.stringify({ ready: next })
      });
    } catch (e) {}
    this.pollLobby();
  },

  copyCode() {
    const code = this.room && this.room.code;
    if (!code) return;
    try {
      navigator.clipboard.writeText(code).then(
        () => TP.ui.toast('코드를 복사했습니다.', 'ok'),
        () => TP.ui.toast('복사에 실패했습니다. 코드를 직접 알려주세요: ' + code, 'warn')
      );
    } catch (e) { TP.ui.toast('복사에 실패했습니다. 코드를 직접 알려주세요: ' + code, 'warn'); }
  },

  renderLobby() {
    const box = $('#duel-box');
    if (!box || !this.room) return;
    const { code, players, playerId } = this.room;
    const me = players.find(p => p.id === playerId);
    box.innerHTML = `
      <button type="button" class="drill-back" id="btn-duel-leave">← 나가기</button>
      <div class="home-hero" style="padding:24px 0 10px">
        <div class="hero-badge">대결 대기실</div>
        <h1 class="hero-title">코드 <em>${code}</em></h1>
        <p class="hero-sub">이 코드를 친구에게 알려주세요. 2명 이상 모두 준비를 마치면 자동으로 시작합니다.</p>
        <button class="btn-ghost" id="btn-duel-copy" style="margin-top:10px">코드 복사</button>
      </div>
      <div class="rk-boardwrap">
        <div class="rk-boardhead">참가자 (${players.length}명)</div>
        <div class="rk-board" id="duel-player-rows"></div>
      </div>
      <div class="rs-actions" style="margin-top:16px">
        <button class="btn-primary btn-huge" id="btn-duel-ready">${me && me.ready ? '준비 취소' : '준비 완료'}</button>
      </div>
    `;
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };

    const rows = box.querySelector('#duel-player-rows');
    if (!players.length) {
      rows.appendChild(H('<p class="lb-empty">참가자를 기다리는 중...</p>'));
    } else {
      players.forEach((p, i) => {
        rows.appendChild(H(`
          <div class="rk-row${p.id === playerId ? ' me' : ''}">
            <span class="rk-r">${i + 1}</span>
            <span class="rk-n">${TP.Leaderboard.esc(p.nick)}</span>
            <span class="rk-t">${p.ready ? '준비완료' : '대기중'}</span>
          </div>`));
      });
    }

    $('#btn-duel-leave', box).onclick = () => this.leaveRoom();
    $('#btn-duel-copy', box).onclick = () => this.copyCode();
    $('#btn-duel-ready', box).onclick = () => this.toggleReady();
  },

  leaveRoom() {
    // 방장이 나가면 방 자체를 지운다 (duel_players 는 room_code 외래키에
    // on delete cascade 가 걸려 있어 참가자 행도 같이 정리된다).
    // 방장이 아니면 서버 쪽 참가자 행은 그대로 두고 이 클라이언트만 빠져나간다
    // — 정리용 크론이 없어도 남은 사람들의 대결 진행에는 지장 없다.
    if (this.room && this.room.isHost) this.deleteRoom();
    this.exit();
  },

  async deleteRoom() {
    if (!this.room || !this.room.code) return;
    const c = TP.Leaderboard.cfg();
    try {
      await fetch(`${c.url}/rest/v1/duel_rooms?code=eq.${enc(this.room.code)}`, {
        method: 'DELETE',
        headers: Object.assign({}, TP.Leaderboard.headers(c), { Prefer: 'return=minimal' })
      });
    } catch (e) {}
  },

  /* ─────────── 카운트다운 · 클릭 대결 ─────────── */
  enterRace() {
    if (!this.room) return;
    this.raceSubmitted = false;
    this.renderRaceWaiting();
    this.scheduleGo();
  },

  renderRaceWaiting() {
    const box = $('#duel-box');
    box.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };
    box.appendChild(H(`
      <div class="standby-wrap" style="grid-template-columns:1fr;text-align:center;min-height:auto;padding:60px 24px">
        <div>
          <div class="sb-label">모두 준비 완료 — 곧 시작합니다</div>
          <div class="sb-count" id="duel-count">-</div>
          <div class="sb-title">신호가 뜨면 최대한 빨리 누르세요</div>
          <button class="btn-primary btn-huge" id="btn-duel-go" disabled style="margin-top:20px;max-width:320px">대기 중...</button>
        </div>
      </div>`));
    this.tickCountdown();
  },

  scheduleGo() {
    const startMs = new Date(this.room.startAt).getTime();
    const wait = Math.max(0, startMs - Date.now());
    clearTimeout(this._goTimer);
    this._goTimer = setTimeout(() => this.armGo(), wait);
    clearInterval(this._cdTimer);
    this._cdTimer = setInterval(() => this.tickCountdown(), 100);
  },

  tickCountdown() {
    const el = $('#duel-count');
    if (!el || !this.room) { clearInterval(this._cdTimer); return; }
    const remain = new Date(this.room.startAt).getTime() - Date.now();
    el.textContent = remain > 0 ? Math.ceil(remain / 1000) : 'GO';
    el.classList.toggle('urgent', remain <= 1000);
  },

  armGo() {
    clearInterval(this._cdTimer);
    const el = $('#duel-count'); if (el) { el.textContent = 'GO'; el.classList.add('urgent'); }
    const btn = $('#btn-duel-go');
    if (!btn) return;
    btn.disabled = false;
    btn.textContent = '지금 예매하기!';
    btn.classList.add('urgent-pulse');
    btn.onclick = () => this.clickGo();
  },

  async clickGo() {
    if (!this.room || this.raceSubmitted) return;
    this.raceSubmitted = true;
    const reactionMs = Math.max(0, Math.round(Date.now() - new Date(this.room.startAt).getTime()));
    const btn = $('#btn-duel-go');
    if (btn) { btn.disabled = true; btn.classList.remove('urgent-pulse'); btn.textContent = `기록 ${TP.u.ms(reactionMs)} · 제출 중...`; }

    const c = TP.Leaderboard.cfg();
    try {
      await fetch(`${c.url}/rest/v1/duel_players?id=eq.${this.room.playerId}`, {
        method: 'PATCH',
        headers: Object.assign({}, TP.Leaderboard.headers(c), { Prefer: 'return=minimal' }),
        body: JSON.stringify({ reaction_ms: reactionMs, finished_at: new Date().toISOString() })
      });
    } catch (e) {}

    this.renderRaceSubmitted(reactionMs);
    this.startResultPoll();
  },

  renderRaceSubmitted(myMs) {
    const box = $('#duel-box');
    box.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };
    box.appendChild(H(`
      <div style="text-align:center;max-width:600px;margin:0 auto">
        <div class="hero-badge">제출 완료</div>
        <h1 class="hero-title" style="font-size:30px;margin-top:14px">내 기록 <em>${TP.u.ms(myMs)}</em></h1>
        <p class="hero-sub">다른 참가자가 끝낼 때까지 자동으로 기다리거나, 바로 결과를 볼 수 있습니다.</p>
        <div class="rk-boardwrap" style="margin-top:20px;text-align:left">
          <div class="rk-boardhead">진행 현황</div>
          <div class="rk-board" id="duel-progress-rows"></div>
        </div>
        <div class="rs-actions" style="margin-top:18px">
          <button class="btn-ghost" id="btn-duel-showresult">결과 바로 보기</button>
        </div>
      </div>`));
    $('#btn-duel-showresult', box).onclick = () => this.showResult();
  },

  startResultPoll() {
    this.stopPoll();
    const tick = async () => {
      if (!this.room) return;
      const c = TP.Leaderboard.cfg();
      try {
        const res = await fetch(
          `${c.url}/rest/v1/duel_players?room_code=eq.${enc(this.room.code)}&select=id,nick,reaction_ms&order=reaction_ms.asc.nullslast`,
          { headers: TP.Leaderboard.headers(c) }
        );
        if (!res.ok || !this.room) return;
        const players = await res.json();
        if (!this.room) return;
        this.room.players = players;
        this.renderProgressRows();
        if (players.length && players.every(p => p.reaction_ms != null)) {
          this.stopPoll();
          this.showResult();
        }
      } catch (e) {}
    };
    tick();
    this._pollTimer = setInterval(tick, 900);
  },

  renderProgressRows() {
    const rows = $('#duel-progress-rows');
    if (!rows || !this.room) return;
    rows.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };
    this.room.players.forEach((p, i) => {
      rows.appendChild(H(`
        <div class="rk-row${p.id === this.room.playerId ? ' me' : ''}">
          <span class="rk-r">${i + 1}</span>
          <span class="rk-n">${TP.Leaderboard.esc(p.nick)}</span>
          <span class="rk-t">${p.reaction_ms == null ? '진행 중...' : TP.u.ms(p.reaction_ms)}</span>
        </div>`));
    });
  },

  /* ─────────── 결과 ─────────── */
  showResult() {
    this.stopPoll();
    if (!this.room) return;
    const box = $('#duel-box');
    box.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };

    const players = (this.room.players || []).slice().sort((a, b) => {
      if (a.reaction_ms == null && b.reaction_ms == null) return 0;
      if (a.reaction_ms == null) return 1;
      if (b.reaction_ms == null) return -1;
      return a.reaction_ms - b.reaction_ms;
    });

    box.appendChild(H(`
      <div style="max-width:640px;margin:0 auto">
        <div class="hero-badge">대결 결과</div>
        <h1 class="hero-title" style="font-size:30px;margin-top:14px">코드 ${this.room.code} 결과</h1>
        <div class="rk-boardwrap" style="margin-top:18px">
          <div class="rk-boardhead">순위</div>
          <div class="rk-board" id="duel-result-rows"></div>
        </div>
        <div class="rs-actions" style="margin-top:20px">
          <button class="btn-primary" id="btn-duel-newroom">새 방 만들기</button>
          <button class="btn-ghost" id="btn-duel-exit">전체 연습으로</button>
        </div>
      </div>`));

    const rows = box.querySelector('#duel-result-rows');
    players.forEach((p, i) => {
      rows.appendChild(H(`
        <div class="rk-row${p.id === this.room.playerId ? ' me' : ''}">
          <span class="rk-r">${p.reaction_ms == null ? '—' : (i + 1) + '위'}</span>
          <span class="rk-n">${TP.Leaderboard.esc(p.nick)}</span>
          <span class="rk-t">${p.reaction_ms == null ? '미제출' : TP.u.ms(p.reaction_ms)}</span>
        </div>`));
    });

    $('#btn-duel-newroom', box).onclick = () => { this.room = null; this.renderHome(); };
    $('#btn-duel-exit', box).onclick = () => this.exit();
  }
};

TP.Duel = Duel;

/* 방장이 나가기 버튼 대신 탭을 그냥 닫거나 새로고침해도 방이 남지 않도록 처리.
   keepalive 로 언로드 중에도 요청이 끝까지 나가게 한다. */
window.addEventListener('pagehide', () => {
  if (!Duel.room || !Duel.room.isHost || !Duel.room.code) return;
  const c = TP.Leaderboard.cfg();
  try {
    fetch(`${c.url}/rest/v1/duel_rooms?code=eq.${enc(Duel.room.code)}`, {
      method: 'DELETE',
      headers: Object.assign({}, TP.Leaderboard.headers(c), { Prefer: 'return=minimal' }),
      keepalive: true
    });
  } catch (e) {}
});

})(window.TP = window.TP || {});
