/* ═══════════════════════════════════════════════
   leaderboard.js — 온라인 랭킹 (Supabase REST)

   예전 커뮤니티 채팅과 같은 방식(REST 직접 호출, 라이브러리 없음)이지만
   훨씬 가볍다. 테이블 1개(점수)뿐이고 방·메시지·실시간 폴링이 없다.

   반응속도는 난이도와 거의 무관한 개인 반사신경 지표이므로(로컬 랭킹도
   난이도로 나누지 않는다), 온라인 랭킹도 난이도 구분 없이 전체를 한 줄로 세운다.
   difficulty 컬럼은 표시용으로만 저장한다.

   접속 정보(프로젝트 URL · anon 키)는 코드에 넣지 않고 결과 화면에서
   입력받아 이 브라우저의 localStorage 에만 저장한다.

   ※ 다른 사람이 보낸 닉네임·난이도는 전부 데이터로만 다룬다.
     HTML 문자열에 합치기 전에 반드시 esc() 로 이스케이프한다.
   ═══════════════════════════════════════════════ */
(function (TP) {

const u = TP.u;

const K_URL = 'ticketrush.lb.url';
const K_KEY = 'ticketrush.lb.key';

/* 사이트 공용 랭킹 서버(Supabase, anon public 키 — 공개돼도 되는 키).
   기기마다 따로 입력하지 않아도 모두 같은 랭킹을 보게 하는 기본값.
   주소·키의 원본은 js/sb.js 한 곳에만 둔다. */
const DEFAULT_URL = TP.SB.URL;
const DEFAULT_KEY = TP.SB.KEY;

const SETUP_SQL =
`create table if not exists public.scores (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  nick         text not null,
  difficulty   text not null,
  reaction_ms  integer not null,
  seat_time_ms integer,
  score        numeric,
  success      boolean not null default false
);

create index if not exists scores_reaction_idx on public.scores (reaction_ms);

alter table public.scores enable row level security;

drop policy if exists "anyone can read"   on public.scores;
drop policy if exists "anyone can insert" on public.scores;

create policy "anyone can read"   on public.scores for select using (true);
create policy "anyone can insert" on public.scores for insert with check (true);`;

const LB = {

  /* ─────────── 접속 설정 ─────────── */
  cfg() {
    try {
      const url = (localStorage.getItem(K_URL) || DEFAULT_URL).trim().replace(/\/+$/, '');
      const key = (localStorage.getItem(K_KEY) || DEFAULT_KEY).trim();
      return url && key ? { url, key } : null;
    } catch (e) {
      return DEFAULT_URL && DEFAULT_KEY ? { url: DEFAULT_URL, key: DEFAULT_KEY } : null;
    }
  },

  saveCfg(url, key) {
    try {
      localStorage.setItem(K_URL, url.trim().replace(/\/+$/, ''));
      localStorage.setItem(K_KEY, key.trim());
    } catch (e) {}
  },

  clearCfg() {
    try { localStorage.removeItem(K_URL); localStorage.removeItem(K_KEY); } catch (e) {}
  },

  /* Supabase 키가 두 형식이다 — 예전 JWT(eyJ...)와 새 Publishable(sb_publishable_...).
     apikey 헤더만으로 role 이 정해지므로, Authorization 은 JWT 일 때만 붙인다. */
  headers(c) {
    const h = { 'apikey': c.key, 'Content-Type': 'application/json' };
    if (/^ey[A-Za-z0-9_-]/.test(c.key)) h['Authorization'] = 'Bearer ' + c.key;
    return h;
  },

  esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, ch => (
      { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]
    ));
  },

  /* 원인을 짐작하지 않고 서버 응답을 그대로 해석한다 (chat.js 에서 검증된 방식) */
  explain(code, body) {
    let j = null;
    try { j = JSON.parse(body); } catch (e) {}
    const msg = (j && (j.message || j.error_description || j.error || j.hint)) || '';
    const pg = (j && j.code) || '';
    const raw = msg ? ` — 서버 메시지: ${msg}` : (body ? ` — ${String(body).slice(0, 140)}` : '');

    if (pg === 'PGRST205' || /schema cache/i.test(msg)) {
      return { kind: 'reload', text: 'SQL 은 성공했지만 API 서버가 아직 새 테이블을 인식하지 못했습니다.' + raw };
    }
    if (pg === '42P01' || /does not exist|relation .* not/i.test(msg)) {
      return { kind: 'sql', text: '점수를 저장할 scores 테이블이 없습니다.' + raw };
    }
    if (pg === '42501' || /permission denied/i.test(msg)) {
      return { kind: 'sql', text: '테이블은 있지만 읽기·쓰기 권한이 없습니다.' + raw };
    }
    if (code === 401 || code === 403) {
      return { kind: 'sql', text: '키가 맞지 않거나 접근 정책이 없습니다. anon public(또는 Publishable) 키인지 확인해 주세요.' + raw };
    }
    if (code === 404) {
      return { kind: 'sql', text: '주소가 Supabase API 주소가 아니거나 테이블이 없습니다.' + raw };
    }
    return { kind: 'sql', text: `서버 오류 ${code}${pg ? ' / ' + pg : ''}${raw}` };
  },

  /** 이번 판을 서버에 등록한다 */
  async submit(row) {
    const c = this.cfg();
    if (!c) return { ok: false };
    try {
      const res = await fetch(`${c.url}/rest/v1/scores`, {
        method: 'POST', headers: this.headers(c), body: JSON.stringify(row)
      });
      if (!res.ok) return Object.assign({ ok: false }, this.explain(res.status, await res.text()));
      return { ok: true };
    } catch (e) {
      return { ok: false, kind: 'net', text: '연결할 수 없습니다. 인터넷 연결을 확인해 주세요.' };
    }
  },

  /** Range 헤더로 실제 행을 받지 않고 개수만 센다 (PostgREST count=exact) */
  async count(c, query) {
    try {
      const res = await fetch(`${c.url}/rest/v1/scores?select=id${query}`, {
        headers: Object.assign({}, this.headers(c), {
          'Prefer': 'count=exact', 'Range-Unit': 'items', 'Range': '0-0'
        })
      });
      if (!res.ok) return Object.assign({ ok: false }, this.explain(res.status, await res.text()));
      const cr = res.headers.get('content-range') || '';
      const total = parseInt(cr.split('/')[1] || '', 10);
      return { ok: true, total: isFinite(total) ? total : 0 };
    } catch (e) {
      return { ok: false, kind: 'net', text: '연결할 수 없습니다. 인터넷 연결을 확인해 주세요.' };
    }
  },

  async board(c, limit) {
    try {
      const url = `${c.url}/rest/v1/scores?select=nick,difficulty,reaction_ms`
        + `&order=reaction_ms.asc&limit=${limit || 10}`;
      const res = await fetch(url, { headers: this.headers(c) });
      if (!res.ok) return Object.assign({ ok: false }, this.explain(res.status, await res.text()));
      return { ok: true, rows: await res.json() };
    } catch (e) {
      return { ok: false, kind: 'net', text: '연결할 수 없습니다. 인터넷 연결을 확인해 주세요.' };
    }
  },

  /**
   * 온라인 랭킹 박스를 그린다. 연결 정보가 없으면 설정 안내를 보여준다.
   * info.reactionMs 가 있으면 이번 기록을 등록하고 내 순위까지 보여주고,
   * 없으면(= 연습을 아직 완료하지 않고 메뉴에서 바로 들어온 경우) 등록 없이
   * 전체 순위판만 보여준다.
   * @param {HTMLElement} box
   * @param {object} info { nick, difficulty, reactionMs, seatTimeMs, score, success }
   */
  async render(box, info) {
    this._lastInfo = info;
    const c = this.cfg();
    if (!c) { this.renderSetup(box); return; }

    box.innerHTML = '<p class="lb-loading">온라인 순위를 불러오는 중...</p>';

    const hasScore = info.reactionMs != null && isFinite(info.reactionMs);
    const myNick = (info.nick || '이름 없음').slice(0, 12);

    // readOnly: 메뉴에서 바로 들어왔을 때(openStandalone) 쓴다.
    // 이전에 완료한 판의 기록으로 순위만 조회할 뿐, 매번 다시 등록하면
    // 화면을 열 때마다 같은 판이 중복으로 쌓인다.
    let sub = { ok: true };
    if (hasScore && !info.readOnly) {
      sub = await this.submit({
        nick: myNick,
        difficulty: info.difficulty,
        reaction_ms: Math.round(info.reactionMs),
        seat_time_ms: info.seatTimeMs == null ? null : Math.round(info.seatTimeMs),
        score: info.score == null ? null : Math.round(info.score * 10) / 10,
        success: !!info.success
      });
      if (!sub.ok) { this.renderError(box, sub); return; }
    }

    const totalRes = await this.count(c, '');
    if (!totalRes.ok) { this.renderError(box, totalRes); return; }
    const total = totalRes.total;

    let rank = null, pct = null;
    if (hasScore) {
      const fasterRes = await this.count(c, `&reaction_ms=lt.${Math.round(info.reactionMs)}`);
      rank = fasterRes.ok ? fasterRes.total + 1 : null;
      pct = (rank != null && total) ? rank / total * 100 : null;
    }

    const boardRes = await this.board(c, 10);

    box.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };

    const mainBlock = hasScore
      ? `<div class="lb-lab">전체 참가자 중 순위</div>
         <div class="lb-rank"><b>${rank == null ? '—' : u.n(rank)}</b><span>/ ${u.n(total)}위</span></div>
         <div class="lb-of">반응속도 기준 · 난이도 구분 없음</div>`
      : `<div class="lb-lab">전체 참가자</div>
         <div class="lb-rank"><b>${u.n(total)}</b><span>명 등록됨</span></div>
         <div class="lb-of">연습을 완료하면 여기에 내 순위도 표시됩니다</div>`;

    box.appendChild(H(`
      <div class="lb-hero">
        <div class="lb-main">${mainBlock}</div>
        ${pct == null ? '' : `
        <div class="lb-side">
          <div class="lb-pct">상위 <b>${TP.rank.fmtPct(pct)}%</b></div>
          <div class="lb-gauge"><i style="width:${u.clamp(pct, 2, 100).toFixed(1)}%"></i></div>
        </div>`}
      </div>
      <div class="lb-boardwrap">
        <div class="lb-boardhead">전체 랭킹 TOP 10</div>
        <div class="lb-board" id="lb-board-rows"></div>
      </div>
      <div class="lb-foot">
        <span>${hasScore && !info.readOnly && sub.ok ? '이번 기록이 방금 등록됐습니다.' : (hasScore ? '가장 최근에 완료한 판 기준입니다.' : '')}</span>
        <button type="button" class="btn-link" id="btn-lb-reset">접속 정보 지우기</button>
      </div>`));

    const rows = boardRes.ok ? boardRes.rows : [];
    const rb = box.querySelector('#lb-board-rows');
    if (!rows.length) {
      rb.appendChild(H('<p class="lb-empty">아직 등록된 기록이 없습니다. 연습을 완료하면 첫 기록이 여기 남습니다.</p>'));
    } else {
      rows.forEach((r, i) => {
        rb.appendChild(H(`
          <div class="lb-row${r.nick === myNick ? ' me' : ''}">
            <span class="lb-r">${i + 1}위</span>
            <span class="lb-n">${this.esc(r.nick)}<em class="lb-d">${this.esc(r.difficulty)}</em></span>
            <span class="lb-t">${u.ms(r.reaction_ms)}</span>
          </div>`));
      });
    }

    box.querySelector('#btn-lb-reset').onclick = () => {
      if (!confirm('저장된 온라인 랭킹 접속 정보를 지울까요?')) return;
      this.clearCfg();
      this.render(box, this._lastInfo);
    };
  },

  renderError(box, e) {
    box.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };
    box.appendChild(H(`
      <div class="lb-fix">
        <b>${this.esc(e.text || '연결 오류가 발생했습니다.')}</b>
        ${e.kind === 'sql' ? `<pre class="svc-sql">${this.esc(SETUP_SQL)}</pre><span>Supabase 대시보드 SQL Editor 에서 실행 후 다시 시도해 주세요.</span>` : ''}
        ${e.kind === 'reload' ? `<pre class="svc-sql">notify pgrst, 'reload schema';</pre><span>이 한 줄만 SQL Editor 에서 실행하면 됩니다.</span>` : ''}
        <div class="lb-fix-actions">
          <button type="button" class="btn-ghost" id="btn-lb-retry">다시 시도</button>
          <button type="button" class="btn-link" id="btn-lb-reset2">접속 정보 지우기</button>
        </div>
      </div>`));
    box.querySelector('#btn-lb-retry').onclick = () => this.render(box, this._lastInfo);
    box.querySelector('#btn-lb-reset2').onclick = () => {
      if (!confirm('저장된 온라인 랭킹 접속 정보를 지울까요?')) return;
      this.clearCfg();
      this.render(box, this._lastInfo);
    };
  },

  renderSetup(box) {
    box.innerHTML = '';
    const H = html => { const d = document.createElement('div'); d.innerHTML = html; return d.firstElementChild; };
    box.appendChild(H(`
      <div class="svc-setup">
        <h2>온라인 랭킹을 켜려면 한 번만 연결하세요</h2>
        <p class="svc-lead">
          다른 사람과 순위를 비교하려면 점수를 모아둘 서버가 필요합니다. 무료 <b>Supabase</b>로 만듭니다.
          <b>접속 정보는 이 브라우저에만 저장</b>되고 제가 볼 수 없습니다.
        </p>
        <ol class="svc-steps">
          <li><b>supabase.com</b> 무료 가입 후 프로젝트 하나를 만듭니다.</li>
          <li><b>SQL Editor</b> 에서 아래 SQL을 붙여넣고 실행합니다.
            <pre class="svc-sql">${this.esc(SETUP_SQL)}</pre>
          </li>
          <li><b>⚙ Project Settings → API</b> (또는 Data API / API Keys) 에서
            Project URL과 anon public(또는 Publishable) 키를 복사해 아래에 넣습니다.
            <br><span class="svc-hint"><b>service_role · Secret key 는 절대 쓰지 마세요</b> — 전체 권한을 가집니다.</span>
          </li>
        </ol>
        <label class="svc-field">
          <span>Project URL</span>
          <input type="text" id="lb-url" placeholder="https://xxxxxxxx.supabase.co" autocomplete="off" spellcheck="false">
        </label>
        <label class="svc-field">
          <span>anon public 키 (또는 Publishable key)</span>
          <input type="text" id="lb-key" placeholder="eyJhbGciOi... 또는 sb_publishable_..." autocomplete="off" spellcheck="false">
        </label>
        <button class="btn-primary" id="btn-lb-save">연결하고 순위 보기</button>
      </div>`));

    box.querySelector('#btn-lb-save').onclick = () => {
      const url = box.querySelector('#lb-url').value;
      const key = box.querySelector('#lb-key').value;
      if (!url.trim() || !key.trim()) { TP.ui.toast('주소와 키를 모두 넣어주세요.', 'warn'); return; }
      this.saveCfg(url, key);
      this.render(box, this._lastInfo);
    };
  },

  /* ─────────── 메뉴에서 바로 들어가는 화면 ───────────
     연습을 완료해야만 온라인 랭킹을 볼 수 있으면 접속 설정을 어디서 하는지
     찾기가 어렵다. 그래서 메뉴에 별도 항목을 두고, 언제든 여기서 연결하고
     전체 랭킹을 볼 수 있게 한다. 가장 최근에 저장된 로컬 기록이 있으면
     그 반응속도로 내 순위도 같이 보여준다 — 없으면 순위판만 보여준다. */
  openStandalone() {
    TP.ui.show('online-rank');
    const btn = document.getElementById('btn-online-home');
    if (btn) {
      btn.onclick = () => {
        if (TP.App && TP.App.goHome) TP.App.goHome();
        else TP.ui.show('home');
      };
    }

    const box = document.getElementById('lb-standalone-box');
    if (!box) return;

    const hist = (TP.store && TP.store.load) ? TP.store.load() : [];
    const last = hist.find((r) => r.reaction != null && isFinite(r.reaction));
    const nick = (TP.rank && TP.rank.player ? TP.rank.player() : '') || '이름 없음';

    this.render(box, {
      nick,
      difficulty: last ? last.difficulty : null,
      reactionMs: last ? last.reaction : null,
      seatTimeMs: last ? last.seatTime : null,
      score: last ? last.score : null,
      success: last ? last.success : false,
      readOnly: true
    });
  }
};

TP.Leaderboard = LB;

})(window.TP = window.TP || {});
