-- ═══════════════════════════════════════════════
--  TicketRush — 방문 통계용 테이블과 조회 함수
--  Supabase 대시보드 → SQL Editor 에 붙여넣고 실행한다.
--
--  ⚠ 아래 'CHANGE-ME-ADMIN-TOKEN' 을 본인만 아는 문자열로 반드시 바꿀 것.
--    관리자 페이지(admin.html)에서 같은 값을 입력해야 통계가 열린다.
--    영문·숫자·하이픈·밑줄만 쓰고 8자 이상을 권장한다.
-- ═══════════════════════════════════════════════

create table if not exists public.visits (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  sid         text not null,      -- 탭 단위 임의 난수. 개인을 식별하지 않는다
  kind        text not null,      -- visit(입장) | stage(화면 이동) | ping(체류 확인) | end(이탈)
  stage       text,               -- 화면 id (home, standby, queue, ...)
  nick        text,               -- 이용자가 정한 표시용 닉네임
  difficulty  text,
  venue       text,
  concert     text,
  device      text,               -- mobile | tablet | desktop
  browser     text,
  os          text,
  ref         text,               -- 유입 경로 호스트 (direct = 직접 방문)
  lang        text,
  tz          text,
  pwa         boolean not null default false,   -- 홈 화면 앱으로 실행 중인지
  is_return   boolean not null default false,   -- 이 브라우저의 재방문인지
  dur_ms      integer                           -- kind='end' 일 때 체류시간
);

create index if not exists visits_created_idx on public.visits (created_at desc);
create index if not exists visits_sid_idx     on public.visits (sid);

alter table public.visits enable row level security;

-- 방문자는 '남기기'만 한다. 읽기 정책을 만들지 않으므로 anon 키로는 아무도 조회할 수 없다.
drop policy if exists "anyone can insert visit" on public.visits;
create policy "anyone can insert visit"
  on public.visits for insert with check (true);

-- 관리자만 토큰으로 조회한다.
-- security definer 라 RLS 를 우회하지만, 토큰이 틀리면 그 전에 막힌다.
create or replace function public.admin_visits(token text, since timestamptz, lim int)
returns setof public.visits
language plpgsql
security definer
set search_path = public
as $$
begin
  if token is distinct from 'CHANGE-ME-ADMIN-TOKEN' then
    raise exception 'unauthorized' using errcode = '42501';
  end if;

  return query
    select * from public.visits
    where created_at >= since
    order by created_at desc
    limit least(coalesce(lim, 20000), 50000);
end;
$$;

revoke all on function public.admin_visits(text, timestamptz, int) from public;
grant execute on function public.admin_visits(text, timestamptz, int) to anon;

-- 스키마 캐시를 즉시 갱신한다 (안 하면 잠깐 'not found' 가 날 수 있다)
notify pgrst, 'reload schema';
